src/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users
end

src/app/models/action.rb
class Action < ApplicationRecord
  has_one :action_plan
end

src/app/models/action_plan.rb
class ActionPlan < ApplicationRecord
  belongs_to :post
  belongs_to :action
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

src/app/models/post.rb
class Post < ApplicationRecord
  has_many :action_plans
  has_many :likes
  has_many :tag_hubs
  belongs_to :user
end

src/app/models/tag.rb
class Tag < ApplicationRecord
end

src/app/models/tag_hub.rb
class TagHub < ApplicationRecord
  belongs_to :post  
end

src/app/models/user.rb
class User < ApplicationRecord
  #userに持たせるやつ
  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest

  has_many :likes
  has_many :posts

  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  #validates :profile_text, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  def User.digest(string)
    #ローカルだからコストを最低にしてるよ！
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #ランダムの文字列の生成とそれをハッシュ化したのをDBに格納するよ
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #パスワードのauthenticateとは別物だよ！こっちはクッキー, emailのトークン。
  def authenticated?(token, attribute)
    digest = send("#{attribute}_digest")
    #digestがないとき例外を出してしまうのでfalseを返す
    return false unless digest

    BCrypt::Password.new(digest).is_password?(token)
  end

  #ログアウトするときに使うよ
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

src/app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    #Userをemailアドレスから見つける
    user = User.find_by(email: params[:email])
    if user && user.authenticated?(params[:id], "activation") && !user.activated?
      user.activate
      log_in user
      flash[:success] = "アカウントが有効化されました"
      redirect_to root_path
    else
      flash[:danger] = "リンクが違いますねえ"
      redirect_to root_path
    end
  end
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

src/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user): forget(user)
        flash[:success] = "Login success"
        redirect_to root_path
      else
        flash[:worning] = "アカウントはまだ無効です。有効化するには届きましたメールからリンクにアクセスしてください"
        redirect_to root_path
      end
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out #if logged_in?
    redirect_to root_path
  end

  private
      def a
      end

end

src/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:success] = "Please check your email to activate your account"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

src/app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  #ブラウザを切っても覚えとくよ
  def remember(user)
    #文字列を生成とし、ハッシュかしたのをDB、
    user.remember
    #生成した文字列をそのままのをクッキーに
    cookies.permanent[:remember_token] = user.remember_token
    #idをクッキーにいれる
    cookies.permanent.signed[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token], "remember")
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user) if logged_in?
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

src/app/helpers/users_helper.rb
module UsersHelper
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Best Practices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <% flash.each do |message_type, message| %>
      <div><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

src/app/views/shared/_error_messages.html.erb

<% if @user.errors %>
  <% @user.errors.full_messages.each do |error|%>
    <li><%= error %></li>
  <% end %>
<% end %>

src/app/views/shared/_header.html.erb
<% if logged_in? %>
  <%= link_to 'プロフ', '#' %>
  <%= link_to 'ログアウト', logout_path, method: :delete %>
<% else %>
  <%= link_to 'home', root_path %>
  <%= link_to 'login', login_path %>
<% end %>

src/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<p>Hello</p>
<%= link_to('登録フォーム', new_user_path, id: 'register_form') %>
<%= link_to('ログイン', login_path) %>

src/app/views/users/new.html.erb
登録フォームだよ
<div>
  <div>
    <%= form_with model: @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create", id: 'create' %>
    <% end %>
  </div>
</div>